import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { appwriteSDK, accountSDK } from '../helper/utils'
import axios from 'axios'

export default function Home() {
    const [file, setFile] = useState<any>(null)
    const [name, setName] = useState('')

    const checkSession = () => {
	const validSession = accountSDK().get()
	validSession
	    .then((response) => { console.log(response) })
	    .catch((error) => {
		accountSDK()
		    .createAnonymousSession()
		    .then((response) => console.log(response))
		    .catch((error) => console.log(error))
	    })
	return
    }

    useEffect(() => {
	checkSession()
    }, [])

    const handleSubmit = async (event: any) => {
	event.preventDefault()	
	console.log(name)
	const sdk = appwriteSDK().createFile('63862be5db006c449939', 'unique()', file)

	await sdk
	    .then((url) => {
		const data = { name, upload: url.$id }
		axios
		    .post(
			'/api/upload',
			JSON.stringify(data),
			{ headers: { 'Content-Type': 'application/json' } },
		    )
		    .then((response) => {
			console.log(response)
			alert('File was uploaded successfully!')
		    })
		    .catch((error) => {
			console.log(error)
		    })
	    })
    }

    return (
	<div>
	    <Head>
		<title>Appwrite DBs</title>
		<meta name='description' content='Generated by create next app'/>
		<link rel='icon' href='/favicon.ico'/>
	    </Head>
	    <main>
		<p>Appwrite Multiple DBs</p>

		<form method='post' onSubmit={handleSubmit}>
		    <fieldset>
			<label htmlFor='name'>
			    Name:
			</label>
			<input
			    type='text'
			    name='name'
			    value={name}
			    required
			    onChange={(event: React.ChangeEvent<HTMLInputElement>) => setName(event.target.value)}
			/>
		    </fieldset>
		    <fieldset>
			<label htmlFor='file'>
			    Select image:
			</label>
			<input
			    type='file'
			    name='file'
			    required
			    onChange={(event: React.ChangeEvent<HTMLInputElement>) => setFile(event.target.files![0])}
			/>
		    </fieldset>
		    <button>Submit</button>
		</form>
	    </main>
	</div>
    )
}
